---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      encoding: utf-8
      standard: ".phpcs/Drupal/ruleset.xml"
      ignore_warnings: true
ratings:
  paths:
  - "./*.module"
  - "./*.install"
  - "./src/**/*.php"
exclude_paths:
- .phpcs
- "**/Test/**/*"
- config
- css
- templates
- tests
