<?php

/**
 * @file
 * Contains moderation_state.module.
 *
 * @todo include UI bits of https://www.drupal.org/node/2429153
 * @todo How to remove the live version (i.e. published => draft without new
 *   revision) - i.e. unpublish
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\moderation_state\BaseFieldInfo;
use Drupal\moderation_state\Plugin\Menu\EditTab;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function workbench_moderation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moderation_state module.
    case 'help.page.workbench_moderation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides basic moderation for content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function workbench_moderation_entity_base_field_info(EntityTypeInterface $entity_type) {
  $base_field_info = new BaseFieldInfo();
  return $base_field_info->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_entity_type_alter().
 */
function workbench_moderation_entity_type_alter(array &$entity_types) {
  \Drupal::service('workbench_moderation.entity_type')->entityTypeAlter($entity_types);
}

/**
 * Implements hook_entity_operation().
 */
function workbench_moderation_entity_operation(EntityInterface $entity) {
  return \Drupal::service('workbench_moderation.entity_type')->entityOperation($entity);
}

/**
 * Sets required flag based on enabled state.
 */
function workbench_moderation_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  return \Drupal::service('workbench_moderation.entity_type')->entityBundleFieldInfoAlter($fields, $entity_type, $bundle);
}

/**
 * Implements hook_entity_presave().
 */
function workbench_moderation_entity_presave(EntityInterface $entity) {
  return \Drupal::service('workbench_moderation.entity_operations')->entityPresave($entity);
}

/**
 * Implements hook_local_tasks_alter().
 */
function workbench_moderation_local_tasks_alter(&$local_tasks) {
  $content_entity_type_ids = array_keys(array_filter(\Drupal::entityTypeManager()->getDefinitions(), function (EntityTypeInterface $entity_type) {
    return $entity_type->isRevisionable();
  }));

  foreach ($content_entity_type_ids as $content_entity_type_id) {
    if (isset($local_tasks["entity.$content_entity_type_id.edit_form"])) {
      $local_tasks["entity.$content_entity_type_id.edit_form"]['class'] = EditTab::class;
      $local_tasks["entity.$content_entity_type_id.edit_form"]['entity_type_id'] = $content_entity_type_id;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function workbench_moderation_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return \Drupal::service('workbench_moderation.entity_type')->bundleFormAlter($form, $form_state, $form_id);
}
