<?php

namespace Drupal\moderation_state\Form;


use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Config\Entity\ConfigEntityTypeInterface;

class EntityWorkflowForm extends EntityForm {

  /**
   * {@inheritdoc}
   *
   * We need to blank out the base form ID so that poorly written form alters
   * that use the base form ID to target both add and edit forms don't pick
   * up our form. This should be fixed in core.
   */
  public function getBaseFormId() {
    return NULL;
  }


  public function form(array $form, FormStateInterface $form_state) {
    /** @var ConfigEntityTypeInterface $entity */
    $entity = $this->entity;

    $form['#markup'] = $this->t('Is this thing on?');

    return parent::form($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritDoc
   */
//  public function buildForm(array $form, FormStateInterface $form_state) {
//
//
//    return $form;
//
//    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
//  }


}
